language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install https://github.com/mysensors/MySensors
    - platformio lib -g install https://github.com/thomasfredericks/Bounce2

   
script: 
    - platformio ci --lib="." --board=uno --board=megaatmega2560 src/MySensor_Gateway.cpp

notifications:
    email:
        on_success: never
        on_failure: always
